spring:
  application:
    name: eureka-server
server:
  port: 8761

#eureka:
# instance:
#   hostname: host-ip
#   preferIpAddress: true
client:
#    not display eureka server as a micro service
    register-with-eureka: false
    fetch-registry: false
#   serviceUrl:
#     defaultZone: http://host-ip/eureka/